import type { Product } from "@/lib/types";

export const featuredProducts: Product[] = [
    {
        id: "prod-core",
        name: "Core Compression Shirt",
        slug: "core-compression-shirt",
        category: "Men's Compression Shirts",
        description:
            "A foundational performance tee engineered for strength work, tempo training, and all-day support.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Athletic fit with a close, performance-driven silhouette.",
        compression: "Performance compression for stabilizing key muscle groups.",
        material: "79% recycled nylon, 21% elastane",
        accent: "Neutral graphite",
        rating: 4.9,
        reviewCount: 351,
        price: 98,
        salePrice: 84,
        images: [
            "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "White", "Navy"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        compressionLevel: "Performance",
        variants: [
            { id: "core-black-m", size: "M", color: "Black", sku: "VOLT-CORE-BLK-M", stock: 12, price: 84 },
            { id: "core-black-l", size: "L", color: "Black", sku: "VOLT-CORE-BLK-L", stock: 6, price: 84 },
            { id: "core-white-m", size: "M", color: "White", sku: "VOLT-CORE-WHT-M", stock: 0, price: 84 },
            { id: "core-navy-s", size: "S", color: "Navy", sku: "VOLT-CORE-NVY-S", stock: 9, price: 84 },
        ],
    },
    {
        id: "prod-apex",
        name: "Apex Compression Shirt",
        slug: "apex-compression-shirt",
        category: "Men's Compression Shirts",
        description:
            "Built for explosive output and hard sessions, with targeted compression that stays dialed under load.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Precision cut to support the torso without restricting movement.",
        compression: "High-tension support with a responsive, locked-in feel.",
        material: "88% polyester, 12% spandex",
        accent: "Performance red",
        rating: 4.8,
        reviewCount: 244,
        price: 108,
        salePrice: 92,
        images: [
            "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "Red", "Grey"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Elite",
        variants: [
            { id: "apex-red-m", size: "M", color: "Red", sku: "VOLT-APEX-RED-M", stock: 8, price: 92 },
            { id: "apex-black-l", size: "L", color: "Black", sku: "VOLT-APEX-BLK-L", stock: 10, price: 92 },
            { id: "apex-grey-xl", size: "XL", color: "Grey", sku: "VOLT-APEX-GRY-XL", stock: 4, price: 92 },
        ],
    },
    {
        id: "prod-velocity",
        name: "Velocity Compression Shirt",
        slug: "velocity-compression-shirt",
        category: "Women's Compression Shirts",
        description:
            "An agile women’s performance tee featuring smooth support, fast drying, and a clean athletic fit.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Tailored contour that follows the body while keeping full range of motion.",
        compression: "Balanced compression for tempo runs, cycling, and strength blocks.",
        material: "82% recycled polyester, 18% elastane",
        accent: "Stealth navy",
        rating: 4.7,
        reviewCount: 287,
        price: 96,
        salePrice: 88,
        images: [
            "https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "Navy", "White"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Performance",
        variants: [
            { id: "velocity-navy-s", size: "S", color: "Navy", sku: "VOLT-VEL-NVY-S", stock: 11, price: 88 },
            { id: "velocity-black-m", size: "M", color: "Black", sku: "VOLT-VEL-BLK-M", stock: 7, price: 88 },
            { id: "velocity-white-l", size: "L", color: "White", sku: "VOLT-VEL-WHT-L", stock: 3, price: 88 },
        ],
    },
    {
        id: "prod-pro-performance",
        name: "Pro Performance Shirt",
        slug: "pro-performance-shirt",
        category: "Men's Compression Shirts",
        description:
            "A premium athletic layer for demanding sessions, designed to support power output and minimize fatigue.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Streamlined fit with enhanced mobility across the shoulders and torso.",
        compression: "Firm compression to keep muscle groups aligned and stable.",
        material: "93% nylon, 7% elastane",
        accent: "Graphite black",
        rating: 4.9,
        reviewCount: 412,
        price: 114,
        salePrice: 102,
        images: [
            "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "Grey", "Red"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        compressionLevel: "Elite",
        variants: [
            { id: "pro-black-m", size: "M", color: "Black", sku: "VOLT-PRO-BLK-M", stock: 14, price: 102 },
            { id: "pro-grey-l", size: "L", color: "Grey", sku: "VOLT-PRO-GRY-L", stock: 5, price: 102 },
            { id: "pro-red-xl", size: "XL", color: "Red", sku: "VOLT-PRO-RED-XL", stock: 2, price: 102 },
        ],
    },
    {
        id: "prod-elite",
        name: "Elite Compression Shirt",
        slug: "elite-compression-shirt",
        category: "Women's Compression Shirts",
        description:
            "Engineered to move seamlessly through fast-paced sessions with relentless support and premium comfort.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "A precise, flattering cut built for form and function.",
        compression: "Recovery-grade pressure that supports circulation and warm-up efficiency.",
        material: "72% nylon, 28% elastane",
        accent: "Clean white",
        rating: 4.8,
        reviewCount: 198,
        price: 110,
        images: [
            "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["White", "Navy", "Black"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Recovery",
        variants: [
            { id: "elite-white-s", size: "S", color: "White", sku: "VOLT-ELITE-WHT-S", stock: 9, price: 110 },
            { id: "elite-navy-m", size: "M", color: "Navy", sku: "VOLT-ELITE-NVY-M", stock: 2, price: 110 },
            { id: "elite-black-l", size: "L", color: "Black", sku: "VOLT-ELITE-BLK-L", stock: 8, price: 110 },
        ],
    },
    {
        id: "prod-motion",
        name: "Motion Compression Shirt",
        slug: "motion-compression-shirt",
        category: "Men's Compression Shirts",
        description:
            "A low-profile performance shirt for training days focused on efficiency, comfort, and mobility.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Minimalist profile with unrestricted shoulder and arm motion.",
        compression: "Moderate, balanced support built for ease throughout the training block.",
        material: "85% polyester, 15% elastane",
        accent: "Midnight navy",
        rating: 4.7,
        reviewCount: 163,
        price: 92,
        images: [
            "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "Navy", "Grey"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Light",
        variants: [
            { id: "motion-black-s", size: "S", color: "Black", sku: "VOLT-MOTION-BLK-S", stock: 16, price: 92 },
            { id: "motion-navy-m", size: "M", color: "Navy", sku: "VOLT-MOTION-NVY-M", stock: 9, price: 92 },
            { id: "motion-grey-l", size: "L", color: "Grey", sku: "VOLT-MOTION-GRY-L", stock: 5, price: 92 },
        ],
    },
    {
        id: "prod-endurance",
        name: "Endurance Compression Shirt",
        slug: "endurance-compression-shirt",
        category: "Women's Compression Shirts",
        description:
            "Purpose-built for long efforts and repeated high output, with stable support and breathable comfort.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Full-range design that supports repeated motion while staying streamlined.",
        compression: "Recovery-first support for long efforts and cooldown phases.",
        material: "79% nylon, 21% elastane",
        accent: "Soft grey",
        rating: 4.8,
        reviewCount: 205,
        price: 100,
        salePrice: 90,
        images: [
            "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Grey", "Black", "Navy"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Recovery",
        variants: [
            { id: "endurance-grey-s", size: "S", color: "Grey", sku: "VOLT-END-GRY-S", stock: 7, price: 90 },
            { id: "endurance-black-m", size: "M", color: "Black", sku: "VOLT-END-BLK-M", stock: 12, price: 90 },
            { id: "endurance-navy-l", size: "L", color: "Navy", sku: "VOLT-END-NVY-L", stock: 4, price: 90 },
        ],
    },
    {
        id: "prod-velocity-ii",
        name: "Velocity II Compression Shirt",
        slug: "velocity-ii-compression-shirt",
        category: "Men's Compression Shirts",
        description:
            "An evolution in everyday performance compressions, balancing support and comfort for long training cycles.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Form-fitting but not restrictive, with a perfectly balanced feel.",
        compression: "Moderate compression with a clean, supportive finish.",
        material: "81% nylon, 19% elastane",
        accent: "Urban red",
        rating: 4.6,
        reviewCount: 121,
        price: 95,
        images: [
            "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Red", "Black", "White"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Performance",
        variants: [
            { id: "velocity2-red-s", size: "S", color: "Red", sku: "VOLT-VELO2-RED-S", stock: 1, price: 95 },
            { id: "velocity2-black-m", size: "M", color: "Black", sku: "VOLT-VELO2-BLK-M", stock: 13, price: 95 },
            { id: "velocity2-white-l", size: "L", color: "White", sku: "VOLT-VELO2-WHT-L", stock: 10, price: 95 },
        ],
    },
    {
        id: "prod-burst",
        name: "Burst Compression Shirt",
        slug: "burst-compression-shirt",
        category: "Women's Compression Shirts",
        description:
            "A sharp, high-output layer designed for fast reps, high velocity training, and quick transitions.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Second-skin performance with a flexible and secure close fit.",
        compression: "High-grade compression with fluid mobility for athletic movement.",
        material: "88% polyester, 12% elastane",
        accent: "Bold red",
        rating: 4.9,
        reviewCount: 174,
        price: 104,
        images: [
            "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Red", "Black", "Navy"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Elite",
        variants: [
            { id: "burst-red-s", size: "S", color: "Red", sku: "VOLT-BURST-RED-S", stock: 6, price: 104 },
            { id: "burst-navy-m", size: "M", color: "Navy", sku: "VOLT-BURST-NVY-M", stock: 8, price: 104 },
            { id: "burst-black-l", size: "L", color: "Black", sku: "VOLT-BURST-BLK-L", stock: 3, price: 104 },
        ],
    },
    {
        id: "prod-pulse",
        name: "Pulse Compression Shirt",
        slug: "pulse-compression-shirt",
        category: "Men's Compression Shirts",
        description:
            "Everyday compression performance with an elevated finish, raw functionality, and premium comfort.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Precision shaping with a flexible, zero-bulk feel.",
        compression: "Responsive compression tuned for strength, speed, and recovery.",
        material: "80% recycled polyester, 20% elastane",
        accent: "Stealth grey",
        rating: 4.8,
        reviewCount: 210,
        price: 99,
        salePrice: 89,
        images: [
            "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Grey", "Black", "White"],
        sizes: ["XS", "S", "M", "L", "XL", "XXL"],
        compressionLevel: "Performance",
        variants: [
            { id: "pulse-grey-m", size: "M", color: "Grey", sku: "VOLT-PULSE-GRY-M", stock: 7, price: 89 },
            { id: "pulse-black-l", size: "L", color: "Black", sku: "VOLT-PULSE-BLK-L", stock: 10, price: 89 },
            { id: "pulse-white-xl", size: "XL", color: "White", sku: "VOLT-PULSE-WHT-XL", stock: 2, price: 89 },
        ],
    },
    {
        id: "prod-kinetic",
        name: "Kinetic Compression Shirt",
        slug: "kinetic-compression-shirt",
        category: "Women's Compression Shirts",
        description:
            "A premium training tee for dynamic movement, cooling comfort, and stable compression under stress.",
        features: [
            "Moisture Wicking",
            "Four-Way Stretch",
            "Breathable Fabric",
            "Muscle Support",
            "Lightweight Construction",
        ],
        fit: "Smooth, sculpted silhouette with full movement flexibility.",
        compression: "Balanced compression to support blood flow and load management.",
        material: "76% nylon, 24% elastane",
        accent: "Midnight black",
        rating: 4.7,
        reviewCount: 143,
        price: 97,
        images: [
            "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1483721310020-03333e577078?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=80",
        ],
        colors: ["Black", "Navy", "White"],
        sizes: ["XS", "S", "M", "L", "XL"],
        compressionLevel: "Recovery",
        variants: [
            { id: "kinetic-black-s", size: "S", color: "Black", sku: "VOLT-KINE-BLK-S", stock: 11, price: 97 },
            { id: "kinetic-navy-m", size: "M", color: "Navy", sku: "VOLT-KINE-NVY-M", stock: 5, price: 97 },
            { id: "kinetic-white-xl", size: "XL", color: "White", sku: "VOLT-KINE-WHT-XL", stock: 4, price: 97 },
        ],
    },
];

const singleProductImage = "/gym.png";

export const allProducts = featuredProducts.map((product) => ({
    ...product,
    images: [singleProductImage, singleProductImage, singleProductImage],
}));

export const reviews = [
    {
        name: "Michael T.",
        product: "Core Compression Shirt",
        rating: 5,
        review: "The fit feels premium and supportive without being restrictive. It stays locked in during heavy lifts and dries fast after sweats.",
    },
    {
        name: "Ariana L.",
        product: "Velocity Compression Shirt",
        rating: 5,
        review: "The compression is just right for runs and tempo work. The fabric is light, breathable, and looks understated but premium.",
    },
    {
        name: "Jordan P.",
        product: "Apex Compression Shirt",
        rating: 4,
        review: "Upper body support is excellent and the stretch is top-tier. I’d buy another in a different color immediately.",
    },
    {
        name: "Riley K.",
        product: "Endurance Compression Shirt",
        rating: 5,
        review: "Super breathable, smooth feel, and it held up through multiple back-to-back training sessions without losing shape.",
    },
];

export const trustStats = [
    { label: "Muscle Support", text: "Targeted compression to keep power and movement in sync." },
    { label: "Sweat-Wicking Fabric", text: "Fast-drying fibers designed for hard training and full recovery." },
    { label: "Four-Way Stretch", text: "Flexibility that moves with your body under pressure." },
    { label: "Breathable Construction", text: "Optimized airflow for heat control and comfort." },
    { label: "Athletic Fit", text: "Streamlined silhouettes built for performance and purpose." },
];
