"use client";

import { useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Product = { id: string; name: string; slug: string; price: string | number; category: string; variants: { id: string; sku: string; color: string; size: string; stock: number; price: string | number }[] };
type Order = { id: string; orderNumber: string; status: string; paymentStatus: string; total: string | number; email: string; items: { name: string; quantity: number }[] };
type Coupon = { id: string; code: string; type: string; value: string | number; active: boolean; usedCount: number; usageLimit: number | null };
type Customer = { id: string; name: string; email: string; _count: { orders: number }; totalSpent: number };

export function AdminPanel() {
    const [tab, setTab] = useState("products");
    const [products, setProducts] = useState<Product[]>([]);
    const [orders, setOrders] = useState<Order[]>([]);
    const [coupons, setCoupons] = useState<Coupon[]>([]);
    const [customers, setCustomers] = useState<Customer[]>([]);
    const [message, setMessage] = useState("");
    const [error, setError] = useState("");
    const load = async () => { const [productsResponse, ordersResponse, couponsResponse, customersResponse] = await Promise.all([fetch("/api/admin/products"), fetch("/api/admin/orders"), fetch("/api/admin/coupons"), fetch("/api/admin/customers")]); if (![productsResponse, ordersResponse, couponsResponse, customersResponse].every((response) => response.ok)) throw new Error("Unable to load admin data."); setProducts(await productsResponse.json()); setOrders(await ordersResponse.json()); setCoupons(await couponsResponse.json()); setCustomers(await customersResponse.json()); };
    useEffect(() => { Promise.all([fetch("/api/admin/products"), fetch("/api/admin/orders"), fetch("/api/admin/coupons"), fetch("/api/admin/customers")]).then(async ([productsResponse, ordersResponse, couponsResponse, customersResponse]) => { if (![productsResponse, ordersResponse, couponsResponse, customersResponse].every((response) => response.ok)) throw new Error("Unable to load admin data."); setProducts(await productsResponse.json()); setOrders(await ordersResponse.json()); setCoupons(await couponsResponse.json()); setCustomers(await customersResponse.json()); }).catch(() => setError("We could not load admin data.")); }, []);
    const update = async (url: string, options: RequestInit) => { setError(""); setMessage(""); const response = await fetch(url, options); const result = await response.json().catch(() => null); if (!response.ok) { setError(result?.error ?? "Update failed."); return; } setMessage("Admin update saved."); await load(); };
    return <section className="mt-10"><div className="flex flex-wrap gap-2">{["products", "inventory", "orders", "coupons", "customers"].map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] ${tab === item ? "bg-[#d8452a] text-white" : "border border-black/10 bg-white text-zinc-700"}`}>{item}</button>)}</div>{error && <p className="mt-4 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{message && <p className="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</p>}
        {tab === "products" && <div className="mt-5 space-y-3">{products.map((product) => <div key={product.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/5 bg-white p-4"><div><div className="font-semibold">{product.name}</div><div className="text-sm text-zinc-500">{product.category} · ${Number(product.price).toFixed(2)} · {product.variants.length} variants</div></div><Button variant="secondary" onClick={() => update(`/api/admin/products/${product.id}`, { method: "DELETE" })}>Delete</Button></div>)}</div>}
        {tab === "inventory" && <div className="mt-5 space-y-3">{products.flatMap((product) => product.variants.map((variant) => <div key={variant.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/5 bg-white p-4"><div><div className="font-semibold">{product.name} · {variant.color} / {variant.size}</div><div className="text-sm text-zinc-500">{variant.sku} · <span className={variant.stock < 1 ? "text-red-600" : variant.stock < 5 ? "text-amber-600" : "text-emerald-600"}>{variant.stock < 1 ? "Out of stock" : variant.stock < 5 ? "Low stock" : "In stock"}</span></div></div><Input className="w-28" type="number" min="0" defaultValue={variant.stock} onBlur={(event) => update(`/api/admin/variants/${variant.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ stock: Number(event.target.value) }) })} /></div>))}</div>}
        {tab === "orders" && <div className="mt-5 space-y-3">{orders.map((order) => <div key={order.id} className="rounded-2xl border border-black/5 bg-white p-4"><div className="flex flex-wrap justify-between gap-3"><span className="font-semibold">#{order.orderNumber}</span><span>{order.email}</span><span>${Number(order.total).toFixed(2)}</span><span>{order.paymentStatus}</span><select value={order.status} onChange={(event) => update(`/api/admin/orders/${order.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: event.target.value }) })} className="rounded-full border border-black/10 px-3 py-1 text-sm"><option>{order.status}</option><option>PROCESSING</option><option>SHIPPED</option><option>DELIVERED</option><option>CANCELLED</option></select></div><div className="mt-2 text-sm text-zinc-500">{order.items.map((item) => `${item.name} × ${item.quantity}`).join(" · ")}</div></div>)}</div>}
        {tab === "coupons" && <div className="mt-5 space-y-3">{coupons.map((coupon) => <div key={coupon.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-black/5 bg-white p-4"><div><div className="font-semibold">{coupon.code}</div><div className="text-sm text-zinc-500">{coupon.type} · {coupon.value} · {coupon.usedCount}/{coupon.usageLimit ?? "∞"}</div></div><div className="flex gap-2"><Button variant="secondary" onClick={() => update(`/api/admin/coupons/${coupon.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !coupon.active }) })}>{coupon.active ? "Disable" : "Enable"}</Button><Button variant="secondary" onClick={() => update(`/api/admin/coupons/${coupon.id}`, { method: "DELETE" })}>Delete</Button></div></div>)}</div>}
        {tab === "customers" && <div className="mt-5 space-y-3">{customers.map((customer) => <div key={customer.id} className="flex flex-wrap justify-between gap-3 rounded-2xl border border-black/5 bg-white p-4"><span className="font-semibold">{customer.name}</span><span>{customer.email}</span><span>{customer._count.orders} orders</span><span>${customer.totalSpent.toFixed(2)} spent</span></div>)}</div>}
    </section>;
}
